import './globals.css'
import { Inter, Poppins } from 'next/font/google'
import Header from './components/Header';

const inter = Inter({ subsets: ['latin'] })
const poppins = Poppins({
  subsets : ['latin'],
  weight: ['400', '700']
});

export const metadata = {
  title: 'My Next13 App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Header />
        <main className='container'>
        {children}
        </main>
      </body>
    </html>
  )
};
